# Site settings
title: _fujo._
description: Modern-Blog
keywords: Modern, Blogging, Fun
author: Fujo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://net-test.siteleaf.net" # the base hostname & protocol for your site, e.g. http://example.commarkdown: kramdown
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
