# Site settings
title: Modern Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://philatist-rat-13667.netlify.com" # the base hostname & protocol for your site, e.g. http://example.commarkdown: kramdown
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
