---
title: Modern Blog
timezone: Africa/Nairobi
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: 
url: http://net-test.siteleaf.net/
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
