---
title: Fujo
timezone: Africa/Nairobi
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

cloudinary:
  cloud_name: tremidus
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 800
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
